name: 'Ensure CI Success'
description: 'Ensure all CI checks and commit statuses pass on a PR'
author: 'Charles de Beauchesne'
inputs:
  initial-delay-seconds:
    description: 'Number of seconds to sleep before checking CI statuses'
    required: false
    default: '5'
  max-retries:
    description: 'Number of retries to wait for checks still in progress'
    required: false
    default: '5'
  polling-interval-seconds:
    description: 'Seconds to wait between retries when checks are still running'
    required: false
    default: '60'
  ignored-name-patterns:
    description: 'List of job name patterns to exclude from evaluation'
    required: false
  github-token:
    description: 'GitHub token to access PR commit statuses and checks'
    required: false
    default: ${{ github.token }}
  full-details-summary:
    description: 'True to display all checks in job summary, false to display only failed checks'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'green'
